### PR TITLE
Add install script

### PR DESCRIPTION
**Pull request by chemzqm**
Using terminal feature for install native module, which requires neovim or vim 8.1.

### CODE REVIEW

**Comment by chemzqm** [comment]
It's failing right now since fruzzy_mod.so is missing from latest tag v0.2.

**Comment by raghur** [comment]
This looks awesome! I've just finally uploaded 0.2 fruzzy_mod.so - so let me know if it works for you now.

**Comment by chemzqm** [comment]
For windows, the file should be removed before download again, just fixed that.

Tested on my Mac and windows10, it works now.

**Comment by raghur** [comment]
Perfect! Thanks a lot for the PR

**Comment by Shougo** [comment]
I have read the code.
The install functions should be in autoload/fruzzy.vim.
I will fix it later.

**Pull request merged**
